
spring:
  cloud:
    config:
      server:
        git:
          password: 
          searchPaths: respo
          uri: https://github.com/forezp/SpringcloudConfig/
          username: 
      label: master
  application:
    name: config-server
server:
  port: 8888
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/